### ISSUE TITLE
locale en_us missing

### ISSUE THREAD

**Issue by lahmann** [finc/docker-vufind2#1]
ICU library < 4.9 has a bug causing formatCurrency to fail if locale has comma as a decimal separator (see also https://bugs.php.net/bug.php?id=53735). VuFind addresses this bug (see https://github.com/vufind-org/vufind/blob/master/module/VuFind/src/VuFind/View/Helper/Root/SafeMoneyFormat.php#L94) by temporary fall-back to locale en_US. As this locale is missing in the current docker-vufind2 image, the workaround will not work and "NaN" is returned with locale de_DE set.
Manually generating locales for `en_US.UTF-8` in the docker container via `dpkg-reconfigure locales` does solve this issue.

**Comment by useltmann** [comment]
the problem was that the choosen locale was misspelled, so that the default locale was used, which was `de_DE.UTF-8`.
the following locales are available in the image:
```
de_DE.UTF-8 UTF-8
en_GB.UTF-8 UTF-8
en_US.UTF-8 UTF-8
```
see https://github.com/smoebody/docker-dev-dotdeb/blob/master/assets/build/locale
