### ISSUE TITLE
Loading "sass.js" tasks...ERROR

### ISSUE THREAD

**Issue by ChristianGiupponi** [finc/docker-vufind2#3]
After I run the command to create the container it starts but fails when try to find Node.

here the issues:

```
Running "scss:sass" (scss) task
2017-03-13 10:15:46,851 INFO spawned: 'solr' with pid 947

Port 8080 is already being used by another process (pid: 759)
Please choose a different port using the -p option.

2017-03-13 10:15:46,994 INFO exited: solr (exit status 1; not expected)
Loading "sass.js" tasks...ERROR
>> Error: Missing binding /usr/local/vufind2/node_modules/node-sass/vendor/linux-x64-51/binding.node
>> Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 7.x
>>
>> Found bindings for the following environments:
>>   - Linux 64-bit with Node 0.10.x
>>
>> This usually happens because your environment has changed since running `npm install`.
>> Run `npm rebuild node-sass` to build the binding for your current environment.
Warning: Task "sass" failed. Use --force to continue.

Aborted due to warnings.
Completed in 6.822s at Mon Mar 13 2017 10:15:47 GMT+0000 (UTC) - Waiting...
2017-03-13 10:15:50,110 INFO spawned: 'solr' with pid 977

Port 8080 is already being used by another process (pid: 759)
Please choose a different port using the -p option.

2017-03-13 10:15:50,236 INFO exited: solr (exit status 1; not expected)
2017-03-13 10:15:51,242 INFO gave up: solr entered FATAL state, too many start retries too quickly
```

**Comment by useltmann** [comment]
please remove the `node_modules` folder from the vufind-folder. when you start the container the node_modules-folder will be set up again. the new image appearently uses a different node version which conflicts with the already installed node_modules.

also i can see that solr is unable to start due to an already used port 8080 can you tell me whether the solr inside the container is working anyways?

**Comment by ChristianGiupponi** [comment]
I have deleted the folder and it continued the installation but fails here:

```
Completed in 10.550s at Mon Mar 13 2017 10:36:52 GMT+0000 (UTC) - Waiting...
2017-03-13 10:36:53,193 INFO spawned: 'solr' with pid 989

Port 8080 is already being used by another process (pid: 767)
Please choose a different port using the -p option.

2017-03-13 10:36:53,326 INFO exited: solr (exit status 1; not expected)
2017-03-13 10:36:54,328 INFO gave up: solr entered FATAL state, too many start retries too quickly
```

I'm on a Mac, and probably there is OSX's Apache running in background

**Comment by useltmann** [comment]
can you provide the complete docker command that you are using to start the container?

**Comment by ChristianGiupponi** [comment]
Sure,

```
docker run --name vufind2-container \
  -v /Users/christiangiupponi/Docker/VuFind:/usr/local/vufind2 \
  -p 127.0.0.1:80:80 \
  -p 127.0.0.1:443:443 \
  -p 127.0.0.1:8080:8080 \
  -p 127.0.0.1:3306:3306 \
  docker.io/ubleipzig/vufind2:php_5.6-1
```

**Comment by useltmann** [comment]
i can confirm that an error occurs while startup, indicating that solr was unable to start. however there *is* a solr up and running, where it is coming from i cannot say by now. can you confirm that there is a solr running on port 8080 after container startup? please go to http://127.0.0.1:8080/ and see whether there is a solr responding

**Comment by ChristianGiupponi** [comment]
Yes, I can see Solr main page

**Comment by useltmann** [comment]
alright, so its the supervisor startup script for solr, which seems to not work properly.

**Comment by useltmann** [comment]
it seems like this is a vufind-issue. i made a ticket https://vufind.org/jira/browse/VUFIND-1224
