### ISSUE TITLE
Start solr

### ISSUE THREAD

**Issue by ChristianGiupponi** [finc/docker-vufind2#5]
I have open a shel and run `chmod +x solr.sh` to give execution permission but when I run:

```./solr.sh start```

I get:

```
root@8b2b2122283b:/usr/local/vufind2# ./solr.sh
Usage: ./solr.sh {start|stop|restart|status}
root@8b2b2122283b:/usr/local/vufind2# ./solr.sh start
Your current version of Java is too old to run this version of Solr
We found version 1.7.0_121, using command 'java'
Please install latest version of Java 8 or set JAVA_HOME properly.

Debug information:
JAVA_HOME: N/A
Active Path:
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@8b2b2122283b:/usr/local/vufind2#
```

**Comment by lahmann** [comment]
Would you please check which VuFind version you are using? The current finc/docker-vufind2 image is not fully compatible to VuFind 4.0 yet (we are working on it), therefore if you are using VuFind 4.0 which comes with Solr 6 (which requires Java 8: https://lucene.apache.org/solr/6_6_1/SYSTEM_REQUIREMENTS.html) it is very likely that you get the reported error message.

**Comment by ChristianGiupponi** [comment]
Probably you're right, I just followed the docs and run:
`git clone https://github.com/vufind-org/vufind.git /home/me/vufind2`

maybe it point to the new version.

I'l try to download it from scratch

**Comment by ChristianGiupponi** [comment]
I tried to use v3.1.2 but:

```
Deprecated: ServiceLocatorAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceLocatorAwareInitializer. Please update your VuFind\Config\PluginManager plugin manager factory to inject the parent service locator via the constructor. in /usr/local/vufind2/vendor/zendframework/zend-mvc/src/Service/ServiceManagerConfig.php on line 175
```

should I open a issue on vufind repo?

**Comment by lahmann** [comment]
Did you do a clean checkout of VuFind 3.1.2 from https://github.com/vufind-org/vufind/releases/tag/v3.1.2 ? The error message looks like some old code got mixed into your VuFind repo.

Long story short:

```
$ git clone https://github.com/vufind-org/vufind.git /home/me/vufind2
$ cd /home/me/vufind2
$ git checkout -b vufind3.1.2 v3.1.2
```
should provide you with a clean VuFind 3.1.2 which _should_ run with the docker image (does run locally for me).

If the deprecated warning persists and you are not using any custom code which might cause the warning, you could check with VuFind 3.1.3 or report the warning finally on the official vufind repo.

**Comment by ChristianGiupponi** [comment]
Tried again and seems to work! Thanks for your support!

**Comment by lahmann** [comment]
Great! :)
